permalink:        pretty

# Setup
title:            "A.P. on code"
tagline:          "A blog by Alex Park"
description:      "A jumble of thoughts on mostly coding, but with other stuff like food and travel thrown in as well."
url:              "https://mrpiao.github.io"
baseurl:          "/"

author:
  name:           "Alex Park"
  url:            "http://alexpark.me"

paginate:         5

github:
  repo:           "https://github.com/MrPiao/mrpiao.github.io"
